routes/web.php
<?php

Route::get('logout_nhan_vien','Controller@logout_nhan_vien')->name('logout_nhan_vien');

Route::group(['middleware' => 'CheckLogin'],function(){
	
	Route::group(['prefix' => 'phong_ban','as' =>'phong_ban.'],function(){
		Route::get('','PhongBanController@view_all')->name('view_all');
		Route::get('view_insert','PhongBanController@view_insert')->name('view_insert');
		Route::post('process_insert','PhongBanController@process_insert')->name('process_insert');

		Route::get('view_update/{ma}','PhongBanController@view_update')->name('view_update');
		Route::post('process_update/{ma}','PhongBanController@process_update')->name('process_update');
		Route::get('delete/{ma}','PhongBanController@delete')->name('delete');



});
Route::group(['prefix' => 'nhan_vien','as' =>'nhan_vien.'],function(){
		Route::get('','NhanVienController@view_all')->name('view_all');
		Route::get('view_insert','NhanVienController@view_insert')->name('view_insert');
		Route::post('process_insert','NhanVienController@process_insert')->name('process_insert');

		Route::get('view_update/{ma}','NhanVienController@view_update')->name('view_update');
		Route::post('process_update/{ma}','NhanVienController@process_update')->name('process_update');
		Route::get('delete/{ma}','NhanVienController@delete')->name('delete');
Route::get('view_nhan_vien_import','NhanVienController@view_nhan_vien_import')->name('view_nhan_vien_import');
Route::post('procces_nhan_vien_import','NhanVienController@procces_nhan_vien_import')->name('procces_nhan_vien_import');
Route::get('view_all_cong','NhanVienController@view_all_cong')->name('view_all_cong');
		

});

	Route::get('view_upload_avatar','Controller@view_upload_avatar')->name('view_upload_avatar');
		Route::post('process_upload_avatar','Controller@process_upload_avatar')->name('process_upload_avatar');



});


Route::get('','Controller@master');
Route::get('view_login','Controller@login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');
Route::get('view_login_nhan_vien','Controller@login_nhan_vien')->name('view_login_nhan_vien');
Route::post('process_login_nhan_vien','Controller@process_login_nhan_vien')->name('process_login_nhan_vien');


Route::group(['middleware' => 'CheckLogin_nhan_vien'],function(){

	Route::group(['prefix' => 'cham_cong','as' =>'cham_cong.'],function(){
		
		Route::get('welcome', 'ChamCongController@welcome')->name('welcome');
        Route::get('check_in', 'ChamCongController@check_in')->name('check_in');
        Route::get('check_out', 'ChamCongController@check_out')->name('check_out');
        Route::get('view_nghi', 'NghiController@view_nghi')->name('view_nghi');
        Route::post('process_nghi', 'NghiController@process_nghi')->name('process_nghi');
        


});

});

app/Http/Controllers/PhongBanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\PhongBan;

class PhongBanController 
{
   public function view_all()
   {
        $array_phong_ban = PhongBan::get();
        return view('phong_ban.view_all',compact('array_phong_ban'));
   }
    public function view_insert()
    
    {

        return view('phong_ban.view_insert');
    }
    public function process_insert(Request $rq)
    {
       
        PhongBan::create($rq->all());
        return redirect()->route('phong_ban.view_all');
    }
   public function view_update($ma){
    $phong_ban = PhongBan::where('ma','=',$ma)->first();
    //$phong_ban = PhongBan::find($ma);
    return view('phong_ban.view_update', compact('phong_ban'));
   }
   public function process_update($ma, Request $rq)
  {
    PhongBan::find($ma)->update($rq->all());

    return redirect()->route('phong_ban.view_all');
  }

   public function delete($ma){

    PhongBan::find($ma)->delete();
      return redirect()->route('phong_ban.view_all');
}
}

resources/views/phong_ban/view_all.blade.php
@extends('layout.master')

@section('content')

<h1>Danh sách phòng ban</h1>
<a href="{{ route('phong_ban.view_insert') }}">Thêm</a>
<table border="1"width="60%">
	<tr>
		<th>Mã</th>
		<th>Tên phòng ban</th>
		
		<th>Sửa</th>
		<th>Xóa</th>
	</tr>
	@foreach ($array_phong_ban as $phong_ban)
	<tr>
		<td>
			{{ $phong_ban->ma }}
		</td>
		<td>
			{{ $phong_ban->ten }}
		</td>
		
		<td>
		<a href="{{ route('phong_ban.view_update',['ma'=> $phong_ban -> ma]) }}">
			Sửa
		</a>	
		</td>
		<td>
		<a href="{{ route('phong_ban.delete',['ma'=> $phong_ban -> ma]) }}">
			xóa
		</a>	
		</td>
	</tr>
	@endforeach
</table>
@endsection

resources/views/phong_ban/view_insert.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('phong_ban.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên phòng ban
	<input type="text" name="ten">

	<button>Thêm</button>
</form>
@endsection

resources/views/phong_ban/view_update.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('phong_ban.process_update',['ma' => $phong_ban->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $phong_ban->ten }}">

	
	<button>Sửa</button>
</form>
@endsection