routes/web.php
<?php

Route::get('logout_nhan_vien','Controller@logout_nhan_vien')->name('logout_nhan_vien');

Route::group(['middleware' => 'CheckLogin'],function(){
	
	Route::group(['prefix' => 'phong_ban','as' =>'phong_ban.'],function(){
		Route::get('','PhongBanController@view_all')->name('view_all');
		Route::get('view_insert','PhongBanController@view_insert')->name('view_insert');
		Route::post('process_insert','PhongBanController@process_insert')->name('process_insert');

		Route::get('view_update/{ma}','PhongBanController@view_update')->name('view_update');
		Route::post('process_update/{ma}','PhongBanController@process_update')->name('process_update');
		Route::get('delete/{ma}','PhongBanController@delete')->name('delete');



});
Route::group(['prefix' => 'nhan_vien','as' =>'nhan_vien.'],function(){
		Route::get('','NhanVienController@view_all')->name('view_all');
		Route::get('view_insert','NhanVienController@view_insert')->name('view_insert');
		Route::post('process_insert','NhanVienController@process_insert')->name('process_insert');

		Route::get('view_update/{ma}','NhanVienController@view_update')->name('view_update');
		Route::post('process_update/{ma}','NhanVienController@process_update')->name('process_update');
		Route::get('delete/{ma}','NhanVienController@delete')->name('delete');
Route::get('view_nhan_vien_import','NhanVienController@view_nhan_vien_import')->name('view_nhan_vien_import');
Route::post('procces_nhan_vien_import','NhanVienController@procces_nhan_vien_import')->name('procces_nhan_vien_import');
Route::get('view_all_cong','NhanVienController@view_all_cong')->name('view_all_cong');
		

});

	Route::get('view_upload_avatar','Controller@view_upload_avatar')->name('view_upload_avatar');
		Route::post('process_upload_avatar','Controller@process_upload_avatar')->name('process_upload_avatar');



});


Route::get('','Controller@master');
Route::get('view_login','Controller@login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');
Route::get('view_login_nhan_vien','Controller@login_nhan_vien')->name('view_login_nhan_vien');
Route::post('process_login_nhan_vien','Controller@process_login_nhan_vien')->name('process_login_nhan_vien');


Route::group(['middleware' => 'CheckLogin_nhan_vien'],function(){

	Route::group(['prefix' => 'cham_cong','as' =>'cham_cong.'],function(){
		
		Route::get('welcome', 'ChamCongController@welcome')->name('welcome');
        Route::get('check_in', 'ChamCongController@check_in')->name('check_in');
        Route::get('check_out', 'ChamCongController@check_out')->name('check_out');
        Route::get('view_nghi', 'NghiController@view_nghi')->name('view_nghi');
        Route::post('process_nghi', 'NghiController@process_nghi')->name('process_nghi');
        


});

});

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html>

<head>
    <!-- Meta and Title -->
    <meta charset="utf-8">
    <title>do_an2</title>
    <meta name="keywords" content="HTML5, Bootstrap 3, Admin Template, UI Theme"/>
    <meta name="description" content="AdminK - A Responsive HTML5 Admin UI Framework">
    <meta name="author" content="ThemeREX">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/img/favicon.png">

    <!-- Angular material -->
    <link rel="stylesheet" type="text/css" href="{{ asset('skin/css/angular-material.min.css')}}">
    
    <!-- Icomoon -->
    <link rel="stylesheet" type="text/css" href="{{ asset('fonts/icomoon/icomoon.css')}}">    
    
    <!-- AnimatedSVGIcons -->
    <link rel="stylesheet" type="text/css" href="{{ asset('fonts/animatedsvgicons/css/codropsicons.css')}}">


    

    <!-- Magnific popup -->
    <link rel="stylesheet" type="text/css" href="{{ asset('js/plugins/magnific/magnific-popup.css')}}">

    <!-- c3charts -->
    <link rel="stylesheet" type="text/css" href="{{ asset('js/plugins/c3charts/c3.min.css')}}">



    <!-- CSS - allcp forms -->
    <link rel="stylesheet" type="text/css" href="{{ asset('allcp/forms/css/forms.css')}}">

    <!-- mCustomScrollbar -->
    <link rel="stylesheet" type="text/css" href="{{ asset('js/utility/malihu-custom-scrollbar-plugin-master/jquery.mCustomScrollbar.min.css')}}">

    <!-- CSS - theme -->
    <link rel="stylesheet" type="text/css" href="{{ asset('skin/default_skin/less/theme.css')}}">


</head>

<body class="dashboard-page with-customizer">

<!-- Body Wrap  -->
<div id="main">

    @include('layout.header')

    @include('layout.sidebar')
    <!-- Main Wrapper -->
    <section id="content_wrapper">

                <!-- Topbar Menu Wrapper -->
    @include('layout.topbar')
       

        <div class="greeting-field">
          
            
        </div>

        <!-- Content -->@yield('content')
        <section id="content" class="table-layout animated fadeIn">

            <!-- Column Center -->
            <div class="chute chute-center">

                <!-- AllCP Info -->
                <div class="allcp-panels fade-onload">

                    <div class="row">
                        <!-- AllCP Grid -->
                        <div class="col-md-12 allcp-grid">
                            
                                                      
                    </div>




                    </div>


                </div>


            </div>
            <!-- /Column Center -->

        </section>
        <!-- /Content -->

        

    </section>
    <!-- /Main Wrapper -->

</div>
<!-- /Body Wrap  -->

<!-- Scripts -->

<!-- jQuery -->
<script src="{{ asset('js/jquery/jquery-1.12.3.min.js')}}"></script>
<script src="{{ asset('js/jquery/jquery_ui/jquery-ui.min.js')}}"></script>

<!-- AnimatedSVGIcons -->
<script src="{{ asset('fonts/animatedsvgicons/js/snap.svg-min.js')}}"></script>
<script src="{{ asset('fonts/animatedsvgicons/js/svgicons-config.js')}}"></script>
<script src="{{ asset('fonts/animatedsvgicons/js/svgicons.js')}}"></script>
<script src="{{ asset('fonts/animatedsvgicons/js/svgicons-init.js')}}"></script>

<!-- Scroll -->
<script src="{{ asset('js/utility/malihu-custom-scrollbar-plugin-master/jquery.mCustomScrollbar.concat.min.js')}}"></script>

<!-- Mixitup -->


<!-- Summernote -->



<!-- HighCharts Plugin -->
<script src="{{ asset('js/plugins/highcharts/highcharts.js')}}"></script>

<!-- Highlight JS -->


<!-- Date/Month - Pickers -->





<!-- Magnific Popup Plugin -->
<script src="{{ asset('js/plugins/magnific/jquery.magnific-popup.js')}}"></script>

<!-- FullCalendar Plugin -->

')}}

<!-- Plugins -->


<script src="{{ asset('js/plugins/c3charts/d3.min.js')}}"></script>
<script src="{{ asset('js/plugins/c3charts/c3.min.js')}}"></script>





<script src="{{ asset('js/plugins/circles/circles.js')}}"></script>




<!-- Google Map API -->





    
<!-- Theme Scripts -->
<script src="{{ asset('js/utility/utility.js')}}"></script>
<script src="{{ asset('js/demo/demo.js')}}"></script>
<script src="{{ asset('js/main.js')}}"></script>
<script src="{{ asset('js/demo/widgets_sidebar.js')}}"></script>

<script src="{{ asset('js/pages/dashboard1.js')}}"></script>

<script src="{{ asset('js/demo/widgets.js')}}"></script>




<!-- /Scripts -->

</body>

</html>

resources/views/layout/sidebar.blade.php
<!-- Sidebar  -->
    <aside id="sidebar_left" class="nano affix">

        <!-- Sidebar Left Wrapper  -->
        <div class="sidebar-left-content nano-content">

            <!-- Sidebar Header -->
            <header class="sidebar-header">

                <!-- Sidebar - Logo -->
                <div class="sidebar-widget logo-widget">
                    <div class="media">
                        <a class="logo-image" href="index.html">
                            <img src="assets/img/logo.png" alt="" class="img-responsive">
                        </a>

                        <div class="logo-slogan">
                            <div><span class="text-info">Phần mềm chấm công</span></div>
                        </div>
                    </div>
                </div>

            </header>
            <!-- /Sidebar Header -->

            <!-- Sidebar Menu  -->
            <ul class="nav sidebar-menu">
                <li class="sidebar-label pt30">Navigation</li>
                <li>
                    <a class="accordion-toggle menu-open" href="#">
                        <span class="caret"></span>
                        <span class="sidebar-title">Dashboard</span>
                        <span class="sb-menu-icon fa fa-home"></span>
                    </a>
                    <ul class="nav sub-nav">
                        <li class="active">
                            <a href="{{ route('phong_ban.view_all') }}">
                                Phòng bàn 
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('nhan_vien.view_all') }}">
                                Nhân viên
                            </a>
                        </li>
                         <li>
                            <a href="{{ route('nhan_vien.view_nhan_vien_import') }}">
                               Import Excel
                            </a>
                        </li>
                      <li>
                            <a href="{{ route('cham_cong.view_nghi') }}">
                               Đăng kí nghỉ
                            </a>
                        </li>
                         <li>
                            <a href="{{ route('nhan_vien.view_all_cong') }}">
                               Quản lý chấm công
                                
                            </a>
                        </li>
                         
                    </ul>
            

            </ul>
            <!-- /Sidebar Menu  -->

        </div>
        <!-- /Sidebar Left Wrapper  -->

    </aside>
    <!-- /Sidebar -->
    