routes/web.php
<?php

Route::get('logout_nhan_vien','Controller@logout_nhan_vien')->name('logout_nhan_vien');

Route::group(['middleware' => 'CheckLogin'],function(){
	
	Route::group(['prefix' => 'phong_ban','as' =>'phong_ban.'],function(){
		Route::get('','PhongBanController@view_all')->name('view_all');
		Route::get('view_insert','PhongBanController@view_insert')->name('view_insert');
		Route::post('process_insert','PhongBanController@process_insert')->name('process_insert');

		Route::get('view_update/{ma}','PhongBanController@view_update')->name('view_update');
		Route::post('process_update/{ma}','PhongBanController@process_update')->name('process_update');
		Route::get('delete/{ma}','PhongBanController@delete')->name('delete');



});
Route::group(['prefix' => 'nhan_vien','as' =>'nhan_vien.'],function(){
		Route::get('','NhanVienController@view_all')->name('view_all');
		Route::get('view_insert','NhanVienController@view_insert')->name('view_insert');
		Route::post('process_insert','NhanVienController@process_insert')->name('process_insert');

		Route::get('view_update/{ma}','NhanVienController@view_update')->name('view_update');
		Route::post('process_update/{ma}','NhanVienController@process_update')->name('process_update');
		Route::get('delete/{ma}','NhanVienController@delete')->name('delete');
Route::get('view_nhan_vien_import','NhanVienController@view_nhan_vien_import')->name('view_nhan_vien_import');
Route::post('procces_nhan_vien_import','NhanVienController@procces_nhan_vien_import')->name('procces_nhan_vien_import');
Route::get('view_all_cong','NhanVienController@view_all_cong')->name('view_all_cong');
		

});

	Route::get('view_upload_avatar','Controller@view_upload_avatar')->name('view_upload_avatar');
		Route::post('process_upload_avatar','Controller@process_upload_avatar')->name('process_upload_avatar');



});


Route::get('','Controller@master');
Route::get('view_login','Controller@login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');
Route::get('view_login_nhan_vien','Controller@login_nhan_vien')->name('view_login_nhan_vien');
Route::post('process_login_nhan_vien','Controller@process_login_nhan_vien')->name('process_login_nhan_vien');


Route::group(['middleware' => 'CheckLogin_nhan_vien'],function(){

	Route::group(['prefix' => 'cham_cong','as' =>'cham_cong.'],function(){
		
		Route::get('welcome', 'ChamCongController@welcome')->name('welcome');
        Route::get('check_in', 'ChamCongController@check_in')->name('check_in');
        Route::get('check_out', 'ChamCongController@check_out')->name('check_out');
        Route::get('view_nghi', 'NghiController@view_nghi')->name('view_nghi');
        Route::post('process_nghi', 'NghiController@process_nghi')->name('process_nghi');
        


});

});

app/Http/Controllers/NhanVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\PhongBan;
use App\Model\NhanVien;
use App\Model\ChamCong;
use App\Imports\NhanVienImport;
use Maatwebsite\Excel\Facades\Excel;
use Session;




class NhanVienController 
{
   public function view_all()
   {
        $array_nhan_vien = NhanVien:: with('phongban')-> get();
        return view('nhan_vien.view_all',compact('array_nhan_vien'));
   }
    public function view_insert()
    
    {
        $array_phong_ban = PhongBan::get();
        return view('nhan_vien.view_insert',compact('array_phong_ban'));
    }
    public function process_insert(Request $rq)
    {
       
        NhanVien::create($rq->all());
        return redirect()->route('nhan_vien.view_all');
    }
   public function view_update($ma){
    $nhan_vien = NhanVien::where('ma','=',$ma)->first();
    $array_phong_ban = PhongBan::get();
    //$nhan_vien = NhanVien::find($ma);
    return view('nhan_vien.view_update', compact('nhan_vien','array_phong_ban'));
   }
   public function process_update($ma, Request $rq)
  {
    NhanVien::find($ma)->update($rq->all());

    return redirect()->route('nhan_vien.view_all');
  }

   public function delete($ma){

    NhanVien::find($ma)->delete();
      return redirect()->route('nhan_vien.view_all');
  }
  public function view_nhan_vien_import(){
    return view('nhan_vien.view_nhan_vien_import');
  }

  public function procces_nhan_vien_import(Request $rq){
     Excel::import(new NhanVienImport, $rq->file_nhan_vien);
     return redirect()->route('nhan_vien.view_all');
  }
  public function view_all_cong()
  {
     $ma_nhan_vien = Session::get('ma_nhan_vien');
     $array_nhan_vien = ChamCong::join('nhan_vien','nhan_vien.ma','cham_cong.ma_nhan_vien')
     -> select('cham_cong.*','nhan_vien.ten')
     -> selectRaw('TIMEDIFF(check_out,check_in) as tong_gio')
     -> get();
    return view('nhan_vien.view_all_cong',compact('array_nhan_vien'));
  }

}

resources/views/nhan_vien/view_all.blade.php
@extends('layout.master')

@section('content')
<h1>Đây là danh sách sinh viên</h1>
<a href="{{ route('nhan_vien.view_insert') }}">Thêm</a>
<table border="1"width="60%">
	<tr>
		<th>Mã</th>
		<th>Tên </th>
		<th>Giới tính</th>
		<th>Tuổi</th>
		<th>Email</th>
		<th>Mật khẩu</th>
		<th>Lương cơ bản</th>
		<th>Tên phòng ban</th>
		<th>Sửa</th>


		
		
	</tr>
	@foreach ($array_nhan_vien as $nhan_vien)
	<tr>
		<td>
			{{ $nhan_vien->ma }}
		</td>
		<td>
			{{ $nhan_vien->ten }}
		</td>
		<td>
			{{ $nhan_vien->ten_gioi_tinh }}
		</td>
		<td>
			{{ $nhan_vien->tuoi }}
		</td>
		<td>
			{{ $nhan_vien->email }}
		</td>
		<td>
			{{ $nhan_vien->mat_khau }}
		</td>
		<td>
			{{ $nhan_vien->luong_co_ban }}
		</td>
	
		<td>
			{{ $nhan_vien->phongban->ten }}
		</td>

		
		<td>

		<a href="{{ route('nhan_vien.view_update',['ma'=> $nhan_vien -> ma]) }}">
			Sửa
		</a>	
		</td>
		<td>
		<a href="{{ route('nhan_vien.delete',['ma'=> $nhan_vien -> ma]) }}">
			xóa
		</a>	
		</td>
	</tr>
	@endforeach
</table>
@endsection

resources/views/nhan_vien/view_all_cong.blade.php
@extends('layout.master')

@section('content')
<h1>Danh sách chấm công nhân viên</h1>
<a href="{{ route('nhan_vien.view_insert') }}">Thêm</a>
<table border="1"width="60%">
	<tr>
		<th>ho ten</th>
		<th>ngay  </th>
		<th>tong so gio</th>	
	</tr>
	@foreach ($array_nhan_vien as $nhan_vien)
	<tr>
		<td>
			{{ $nhan_vien-> ten }}
		</td>
		<td>
			{{ $nhan_vien -> ngay }}
		</td>
		<td>{{ $nhan_vien -> tong_gio }}</td>
	</tr>
	@endforeach
</table>
@endsection

resources/views/nhan_vien/view_insert.blade.php
@extends('layout.master')

@section('content')

<form action="{{ route('nhan_vien.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên nhân viên
	<input type="text" name="ten">
	<br>  
	Giới tính
	<input type="radio" name="gioi_tinh" value="1">Nam
	<input type="radio" name="gioi_tinh" value="0">Nữ
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh">
	<br>
	Email
	<input type="text" name="email">
	<br>
	Mật khẩu
	<input type="password" name="mat_khau">
	<br>
	Lương cơ bản
	<input type="text" name="luong_co_ban">
	<br>
	
	Phòng ban
	<select name="ma_phong_ban">
		@foreach($array_phong_ban as $phong_ban)
		<option value="{{ $phong_ban->ma }}">
			{{ $phong_ban->ten }}
		</option>
		@endforeach
		
	</select>



	
<br>
	<button>Thêm</button>
</form>
@endsection

resources/views/nhan_vien/view_nghi.blade.php
@extends('layout.master')

@section('content')
<h1>Đăng kí buổi nghỉ</h1>

@if(!isset($nghi))
	<form action="{{ route('cham_cong.process_nghi') }}" method="post">
		{{ csrf_field() }}
		<input type="date" name="ngay_nghi">
		<br>
		<button>đăng kí</button>
	</form>
	
@endif
@endsection

resources/views/nhan_vien/view_nhan_vien_import.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('nhan_vien.procces_nhan_vien_import') }}" method="post" enctype="multipart/form-data">
	{{ csrf_field() }}
	chọn file excel
	<input type="file" name="file_nhan_vien">
	<br>
	<button>chọn</button>
	
</form>
@endsection

resources/views/nhan_vien/view_update.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('nhan_vien.process_update',['ma' => $nhan_vien->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $nhan_vien->ten }}">
	<br>  
	Giới tính
	<input type="radio" name="gioi_tinh" value="1"
		@if($nhan_vien->gioi_tinh==1)
			checked
		@endif
	>Nam
	<input type="radio" name="gioi_tinh" value="0"
		@if($nhan_vien->gioi_tinh==0)
			checked
		@endif
	>Nữ
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh" value="{{ $nhan_vien->ngay_sinh }}">
	<br>
	Email
	<input type="text" name="email" value="{{ $nhan_vien->email }}">
	<br>
	Mật khẩu
	<input type="password" name="mat_khau" value="{{ $nhan_vien->mat_khau }}">
	<br>
	Lương cơ bản
	<input type="text" name="luong_co_ban" value="{{ $nhan_vien->luong_co_ban }}">
	<br>
	
	Phòng ban
	<select name="ma_phong_ban">
		@foreach($array_phong_ban as $phong_ban)
		<option value="{{ $phong_ban->ma }}"
			@if($nhan_vien->ma_phong_ban==$phong_ban->ma)
			selected
		@endif
			>
			{{ $phong_ban->ten }}
		</option>
		@endforeach
		
	</select>



	
<br>
	

	
	<button>Sửa</button>
</form>
@endsection